-- Extraído de un objeto FastReport FRSql. Parámetros originales preservados.

WITH CLIENTES AS (
Select
PED_CLIENTEENC.CTECLI_CODIGO_K
FROM
PED_CLIENTEENC
WHERE
PED_CLIENTEENC.PEDCTE_FECHAENT >= @FECHAINI
AND  PED_CLIENTEENC.PEDCTE_FECHAENT <= @FECHAFIN
AND  PED_CLIENTEENC.S_MAQEDO <> 40
GROUP BY
PED_CLIENTEENC.CTECLI_CODIGO_K
)
SELECT
s.SYSUDN_CODIGO_K AS UDN,
d.S_MAQEDO AS estado_sistema,
CASE WHEN CLIENTES.CTECLI_CODIGO_K IN ('TIPO_CONTADO', 'CTE_ESP_01' ) THEN CONCAT (CLIENTES.CTECLI_CODIGO_K, '-', S.SYSUDN_CODIGO_K)
WHEN CLIENTES.CTECLI_CODIGO_K='CTE_ESP_02' AND s.SYSUDN_CODIGO_K='UDN_01' THEN 'CTE_ESP_02_01'
WHEN CLIENTES.CTECLI_CODIGO_K='CTE_ESP_02' AND s.SYSUDN_CODIGO_K='UDN_04' THEN 'CTE_ESP_02_04'
ELSE CLIENTES.CTECLI_CODIGO_K
END AS cod_cliente,
d.CTEDIR_CODIGO_K AS cod_directorio,
d.CTECLI_RAZONSOCIAL AS razon_social,
d.CTECLI_DENCOMERCIA AS den_comercial,
d.CTEDIR_TIPOFIS AS tipo_fiscal,
d.CTEDIR_TIPOENT AS tipo_entrega,
d.CTEDIR_RESPONSABLE AS responsable,
d.CTEDIR_TELEFONO AS telefono,
d.CTEDIR_CALLE AS calle,
d.CTEDIR_CALLENUMEXT AS num_calle_ext,
d.CTEDIR_CALLENUMINT AS num_calle_int,
d.CTEDIR_COLONIA AS colonia,
d.CTEDIR_CALLEENTRE1 AS entrecalle1,
d.CTEDIR_CALLEENTRE2 AS entrecalle2,
d.CTEDIR_CP AS cp,
d.MAP_X AS map_x,
d.MAP_Y AS map_y,
d.CTEDIR_OBSERVACIONES AS observaciones,
d.CTEPFR_CODIGO_K AS frecuencia,
d.VTARUT_CODIGO_K_PRE AS ruta_preventa,
d.VTARUT_CODIGO_K_ENT AS ruta_entrega,
d.VTARUT_CODIGO_K_AUT AS ruta_autoventa,
d.S_GUID AS S_GUID,
d.CTEDIR_SECUENCIA AS secuencia,
d.CTEDIR_SECUENCIAENT AS secuencia_ent,
d.S_FECHA AS fecha_alta,
d.CTEPAQ_CODIGO_K AS paq_servicio,
d.CTEDIR_MAIL AS correo,
d.CTEDIR_EDOCRED AS estado_credito,
d.CTEDIR_DIASCREDITO AS dias_credito,
d.CTEDIR_LIMITECREDI AS limite_credito,
d.CTEDIR_CREDITOOBS AS observaciones_cred,
d.SATCP_CODIGO_K AS cp_sat
FROM CLIENTES
LEFT JOIN CTE_DIRECCION d ON CLIENTES.CTECLI_CODIGO_K = d.CTECLI_CODIGO_K
CROSS JOIN SYS_UDN s
WHERE s.SYSUDN_CODIGO_K = CASE WHEN @DFT_UDN IN ('UDN_05','UDN_06','UDN_04') THEN 'UDN_04' ELSE 'UDN_01' END
UNION
SELECT
s.SYSUDN_CODIGO_K AS UDN,
d.S_MAQEDO AS estado_sistema,
CASE WHEN d.CTECLI_CODIGO_K IN ('TIPO_CONTADO', 'CTE_ESP_01' ) THEN CONCAT (d.CTECLI_CODIGO_K, '-', S.SYSUDN_CODIGO_K)
WHEN d.CTECLI_CODIGO_K='CTE_ESP_02' AND s.SYSUDN_CODIGO_K='UDN_01' THEN 'CTE_ESP_02_01'
WHEN d.CTECLI_CODIGO_K='CTE_ESP_02' AND s.SYSUDN_CODIGO_K='UDN_04' THEN 'CTE_ESP_02_04'
ELSE d.CTECLI_CODIGO_K
END AS cod_cliente,
d.CTEDIR_CODIGO_K AS cod_directorio,
d.CTECLI_RAZONSOCIAL AS razon_social,
d.CTECLI_DENCOMERCIA AS den_comercial,
d.CTEDIR_TIPOFIS AS tipo_fiscal,
d.CTEDIR_TIPOENT AS tipo_entrega,
d.CTEDIR_RESPONSABLE AS responsable,
d.CTEDIR_TELEFONO AS telefono,
d.CTEDIR_CALLE AS calle,
d.CTEDIR_CALLENUMEXT AS num_calle_ext,
d.CTEDIR_CALLENUMINT AS num_calle_int,
d.CTEDIR_COLONIA AS colonia,
d.CTEDIR_CALLEENTRE1 AS entrecalle1,
d.CTEDIR_CALLEENTRE2 AS entrecalle2,
d.CTEDIR_CP AS cp,
d.MAP_X AS map_x,
d.MAP_Y AS map_y,
d.CTEDIR_OBSERVACIONES AS observaciones,
d.CTEPFR_CODIGO_K AS frecuencia,
d.VTARUT_CODIGO_K_PRE AS ruta_preventa,
d.VTARUT_CODIGO_K_ENT AS ruta_entrega,
d.VTARUT_CODIGO_K_AUT AS ruta_autoventa,
d.S_GUID AS S_GUID,
d.CTEDIR_SECUENCIA AS secuencia,
d.CTEDIR_SECUENCIAENT AS secuencia_ent,
d.S_FECHA AS fecha_alta,
d.CTEPAQ_CODIGO_K AS paq_servicio,
d.CTEDIR_MAIL AS correo,
d.CTEDIR_EDOCRED AS estado_credito,
d.CTEDIR_DIASCREDITO AS dias_credito,
d.CTEDIR_LIMITECREDI AS limite_credito,
d.CTEDIR_CREDITOOBS AS observaciones_cred,
d.SATCP_CODIGO_K AS cp_sat
FROM CTE_DIRECCION d
CROSS JOIN SYS_UDN s
WHERE d.S_MAQEDO = 10
AND s.SYSUDN_CODIGO_K = CASE WHEN @DFT_UDN IN ('UDN_05','UDN_06','UDN_04') THEN 'UDN_04' ELSE 'UDN_01' END
ORDER BY
estado_sistema DESC,
fecha_alta ASC;
