-- Extraído de un objeto FastReport FRSql. Parámetros originales preservados.

WITH CLIENTES AS (
Select
PED_CLIENTEENC.CTECLI_CODIGO_K
FROM
PED_CLIENTEENC
WHERE
PED_CLIENTEENC.PEDCTE_FECHAENT >= @FECHAINI
AND  PED_CLIENTEENC.PEDCTE_FECHAENT <= @FECHAFIN
AND  PED_CLIENTEENC.S_MAQEDO <> 40
GROUP BY
PED_CLIENTEENC.CTECLI_CODIGO_K
)
SELECT
s.SYSUDN_CODIGO_K AS UDN,
a.S_MAQEDO AS ESTADO,
CASE WHEN CLIENTES.CTECLI_CODIGO_K IN ('TIPO_CONTADO', 'CTE_ESP_01' ) THEN CONCAT (CLIENTES.CTECLI_CODIGO_K, '-', S.SYSUDN_CODIGO_K)
WHEN CLIENTES.CTECLI_CODIGO_K='CTE_ESP_02' AND s.SYSUDN_CODIGO_K='UDN_01' THEN 'CTE_ESP_02_01'
WHEN CLIENTES.CTECLI_CODIGO_K='CTE_ESP_02' AND s.SYSUDN_CODIGO_K='UDN_04' THEN 'CTE_ESP_02_04'
ELSE CLIENTES.CTECLI_CODIGO_K
END AS CODIGO,
a.CTECLI_RAZONSOCIAL AS Razon_Social,
a.CTECLI_DENCOMERCIA AS CLIENTE,
a.CTECLI_RFC AS RFC,
a.CTECLI_FECHAALTA AS FECHA_ALTA,
a.CTECLI_FECHABAJA AS FECHA_BAJA,
a.CTECLI_CONTACTO AS CONTACTO,
a.CTECLI_VALES AS VALES,
a.CTECLI_EDOCRED AS ESTADO_CRED,
a.CTECLI_DIASCREDITO AS DIAS_CRED,
a.CTECLI_LIMITECREDI AS LIMITE_CRED,
a.CTECLI_OBSERVACIONES AS OBSERVACIONES,
a.CTECLI_CREDITOOBS AS OBSERVACIONES_CRED
FROM CLIENTES
LEFT JOIN CTE_CLIENTE a ON CLIENTES.CTECLI_CODIGO_K = a.CTECLI_CODIGO_K
CROSS JOIN SYS_UDN s
WHERE s.SYSUDN_CODIGO_K = CASE WHEN @DFT_UDN IN ('UDN_05','UDN_06','UDN_04') THEN 'UDN_04' ELSE 'UDN_01' END
UNION
SELECT
s.SYSUDN_CODIGO_K AS UDN,
a.S_MAQEDO AS ESTADO,
CASE WHEN a.CTECLI_CODIGO_K IN ('TIPO_CONTADO', 'CTE_ESP_01' ) THEN CONCAT (a.CTECLI_CODIGO_K, '-', S.SYSUDN_CODIGO_K)
WHEN a.CTECLI_CODIGO_K='CTE_ESP_02' AND s.SYSUDN_CODIGO_K='UDN_01' THEN 'CTE_ESP_02_01'
WHEN a.CTECLI_CODIGO_K='CTE_ESP_02' AND s.SYSUDN_CODIGO_K='UDN_04' THEN 'CTE_ESP_02_04'
ELSE a.CTECLI_CODIGO_K
END AS CODIGO,
a.CTECLI_RAZONSOCIAL AS Razon_Social,
a.CTECLI_DENCOMERCIA AS CLIENTE,
a.CTECLI_RFC AS RFC,
a.CTECLI_FECHAALTA AS FECHA_ALTA,
a.CTECLI_FECHABAJA AS FECHA_BAJA,
a.CTECLI_CONTACTO AS CONTACTO,
a.CTECLI_VALES AS VALES,
a.CTECLI_EDOCRED AS ESTADO_CRED,
a.CTECLI_DIASCREDITO AS DIAS_CRED,
a.CTECLI_LIMITECREDI AS LIMITE_CRED,
a.CTECLI_OBSERVACIONES AS OBSERVACIONES,
a.CTECLI_CREDITOOBS AS OBSERVACIONES_CRED
FROM CTE_CLIENTE a
CROSS JOIN SYS_UDN s
WHERE a.S_MAQEDO = 10
AND s.SYSUDN_CODIGO_K = CASE WHEN @DFT_UDN IN ('UDN_05','UDN_06','UDN_04') THEN 'UDN_04' ELSE 'UDN_01' END
ORDER BY
ESTADO DESC,
FECHA_ALTA ASC;
