-- Extraído de un objeto FastReport FRSql. Parámetros originales preservados.

WITH TMP_VENTAS1 AS (
SELECT
ENC.SYSUDN_CODIGO_K,
ENC.LIQUID_REFERENCIA,
ENC.CTECLI_CODIGO_K,
DET.PRODUC_CODIGO_K,
PRO.PRODUC_DESCRIPCION,
PRO.PROPRE_CODIGO_K,
ENC.FACDOC_FECHA,
( CASE WHEN ENC.FACDOC_CREDDIAS > 0 THEN 'TIPO_CREDITO' ELSE 'TIPO_CONTADO' END ) TPO_VTA,
SUM(DET.FACDOCD_CANTIDAD) AS PIEZAS,
DET.FACDOCD_COSTO AS COSTO,
( CASE WHEN ENC.FACDOC_CREDDIAS > 0 THEN COALESCE(SUM(-DET.FACDOCD_COSTO * DET.FACDOCD_CANTIDAD), 0) ELSE COALESCE(SUM(-DET.FACDOCD_COSTO * DET.FACDOCD_CANTIDAD), 0) END) AS VENTA
FROM
FAC_DOCUMENTO ENC,
FAC_DETALLE DET,
PRO_PRODUCTO PRO
WHERE
ENC.SYSUDN_CODIGO_K = DET.SYSUDN_CODIGO_K
AND ENC.SYSTRA_CODIGO_K = DET.SYSTRA_CODIGO_K
AND ENC.FACDOC_SERIE_K = DET.FACDOC_SERIE_K
AND ENC.FACDOC_FOLIO_K = DET.FACDOC_FOLIO_K
AND DET.PRODUC_CODIGO_K = PRO.PRODUC_CODIGO_K
AND ENC.SYSUDN_CODIGO_K IN ('UDN_01','UDN_02','UDN_03','UDN_04','UDN_05','UDN_06')
AND ENC.FACDOC_FECHA BETWEEN @FECHA_INI AND @FECHA_FIN
AND DET.PRODUC_CODIGO_K BETWEEN '00' AND 'zz'
AND ENC.LIQUID_REFERENCIA IS NOT NULL
GROUP BY
ENC.SYSUDN_CODIGO_K,
ENC.LIQUID_REFERENCIA,
ENC.CTECLI_CODIGO_K,
DET.PRODUC_CODIGO_K,
PRO.PRODUC_DESCRIPCION,
PRO.PROPRE_CODIGO_K,
ENC.FACDOC_CREDDIAS,
ENC.FACDOC_FECHA,
DET.FACDOCD_COSTO
UNION ALL
SELECT
ENC.SYSUDN_CODIGO_K,
ENC.LIQUID_REFERENCIA,
ENC.CTECLI_CODIGO_K,
DET.PRODUC_CODIGO_K,
PRO.PRODUC_DESCRIPCION,
PRO.PROPRE_CODIGO_K,
ENC.PEDCTE_FECHAENT AS FACDOC_FECHA,
( CASE WHEN ENC.PEDCTE_CREDDIAS > 0 THEN 'TIPO_CREDITO' ELSE 'TIPO_CONTADO' END ) TPO_VTA,
SUM(DET.PEDCTED_CANTLIQ) AS PIEZAS,
DET.PEDCTED_COSTO AS COSTO,
( CASE WHEN ENC.PEDCTE_CREDDIAS > 0 THEN COALESCE(SUM(-DET.PEDCTED_COSTO * DET.PEDCTED_CANTLIQ), 0) ELSE COALESCE(SUM(DET.PEDCTED_COSTO * DET.PEDCTED_CANTLIQ), 0) END) AS VENTA
FROM
PED_CLIENTEENC ENC,
PED_CLIENTEDET DET,
PRO_PRODUCTO PRO
WHERE
ENC.SYSUDN_CODIGO_K = DET.SYSUDN_CODIGO_K
AND ENC.SYSTRA_CODIGO_K = DET.SYSTRA_CODIGO_K
AND ENC.PEDCTE_SERIE_K = DET.PEDCTE_SERIE_K
AND ENC.PEDCTE_FOLIO_K = DET.PEDCTE_FOLIO_K
AND DET.PRODUC_CODIGO_K = PRO.PRODUC_CODIGO_K
AND ENC.SYSUDN_CODIGO_K IN ('UDN_01','UDN_02','UDN_03','UDN_04','UDN_05','UDN_06')
AND ENC.PEDCTE_FECHAENT BETWEEN @FECHA_INI AND @FECHA_FIN
AND DET.PRODUC_CODIGO_K BETWEEN '00' AND 'zz'
AND ENC.LIQUID_REFERENCIA IS NOT NULL
AND ENC.S_MAQEDO NOT IN (40)
AND ENC.CTECLI_CODIGO_K NOT IN ('CTE_ESP_01')
GROUP  BY
ENC.SYSUDN_CODIGO_K,
ENC.LIQUID_REFERENCIA,
ENC.CTECLI_CODIGO_K,
DET.PRODUC_CODIGO_K,
PRO.PRODUC_DESCRIPCION,
PRO.PROPRE_CODIGO_K,
ENC.PEDCTE_FECHAENT,
ENC.PEDCTE_CREDDIAS,
DET.PEDCTED_COSTO
UNION ALL
SELECT
EFE.SYSUDN_CODIGO_K,
EFE.LIQUID_REFERENCIA,
'' AS CTECLI_CODIGO_K,
DET.PRODUC_CODIGO_K AS PRODUC_CODIGO_K,
TRA.SYSTTS_DESCRIPCION AS PRODUC_DESCRIPCION,
EFE.SYSTTP_CODIGO_K AS PROPRE_CODIGO_K,
EFE.LIQCEF_FECHA AS FACDOC_FECHA,
'CARGO' AS TPO_VTA,
DET.ELIQCE_CANTIDAD AS PIEZAS,
0.0 AS COSTO,
0.0 AS VENTA
FROM
LIQ_CARGOEFE EFE
LEFT JOIN ELLIQ_CARGOEFEDET DET ON
EFE.SYSUDN_CODIGO_K = DET.SYSUDN_CODIGO_K
AND EFE.SYSTRA_CODIGO_K = DET.SYSTRA_CODIGO_K
AND EFE.LIQCEF_SERIE_K = DET.LIQCEF_SERIE_K
AND EFE.LIQCEF_FOLIO_K = DET.LIQCEF_FOLIO_K
LEFT JOIN  SYS_TRANSACSUBTIPO TRA ON
TRA.SYSTRA_CODIGO_K = EFE.SYSTRA_CODIGO_K
AND TRA.SYSTTP_CODIGO_K = EFE.SYSTTP_CODIGO_K
AND TRA.SYSTTS_CODIGO_K = EFE.SYSTTS_CODIGO_K
WHERE EFE.SYSUDN_CODIGO_K IN ('UDN_01','UDN_02','UDN_03','UDN_04','UDN_05','UDN_06')
AND EFE.LIQCEF_FECHA BETWEEN @FECHA_INI AND @FECHA_FIN
AND DET.PRODUC_CODIGO_K BETWEEN '00' AND 'zz'
AND EFE.S_MAQEDO <> 20
GROUP  BY
EFE.SYSUDN_CODIGO_K,
EFE.LIQUID_REFERENCIA,
DET.PRODUC_CODIGO_K,
TRA.SYSTTS_DESCRIPCION,
EFE.SYSTTP_CODIGO_K,
EFE.LIQCEF_FECHA,
DET.ELIQCE_CANTIDAD
UNION ALL
SELECT
ENC.SYSUDN_CODIGO_K,
ENC.LIQUID_REFERENCIA,
'' AS CTECLI_CODIGO_K,
DET.PRODUC_CODIGO_K AS PRODUC_CODIGO_K,
PRO.PRODUC_DESCRIPCION  + ' - ' + TRA.SYSTTS_DESCRIPCION  AS PRODUC_DESCRIPCION,
--PRO.PRODUC_DESCRIPCION AS PRODUC_DESCRIPCION2,
ENC.SYSTTP_CODIGO_K AS PROPRE_CODIGO_K,
ENC.LIQBES_FECHA AS FACDOC_FECHA,
'BONIFICACION' AS TPO_VTA,
DET.LIQBESD_CANTIDAD AS PIEZAS,
0.0 AS COSTO,
0.0 AS VENTA
FROM
LIQ_BONESPENC ENC LEFT JOIN
LIQ_BONESPDET DET ON
ENC.SYSUDN_CODIGO_K = DET.SYSUDN_CODIGO_K
AND ENC.SYSTRA_CODIGO_K = DET.SYSTRA_CODIGO_K
AND ENC.LIQBES_SERIE_K = DET.LIQBES_SERIE_K
AND ENC.LIQBES_FOLIO_K = DET.LIQBES_FOLIO_K
INNER JOIN PRO_PRODUCTO PRO ON
DET.PRODUC_CODIGO_K = PRO.PRODUC_CODIGO_K
LEFT JOIN  SYS_TRANSACSUBTIPO TRA ON
TRA.SYSTRA_CODIGO_K = ENC.SYSTRA_CODIGO_K
AND TRA.SYSTTP_CODIGO_K = ENC.SYSTTP_CODIGO_K
AND TRA.SYSTTS_CODIGO_K = ENC.SYSTTS_CODIGO_K
WHERE ENC.SYSUDN_CODIGO_K IN ('UDN_01','UDN_02','UDN_03','UDN_04','UDN_05','UDN_06')
AND ENC.LIQBES_FECHA BETWEEN @FECHA_INI AND @FECHA_FIN
AND DET.PRODUC_CODIGO_K BETWEEN '00' AND 'zz'
AND ENC.S_MAQEDO <> '20'
GROUP  BY
ENC.SYSUDN_CODIGO_K,
ENC.LIQUID_REFERENCIA,
DET.PRODUC_CODIGO_K,
TRA.SYSTTS_DESCRIPCION,
PRO.PRODUC_DESCRIPCION,
ENC.SYSTTP_CODIGO_K,
ENC.LIQBES_FECHA,
DET.LIQBESD_CANTIDAD
UNION ALL
SELECT
ENC.SYSUDN_CODIGO_K,
ENC.LIQUID_REFERENCIA,
'' AS CTECLI_CODIGO_K,
DET.PRODUC_CODIGO_K AS PRODUC_CODIGO_K,
TPO.SYSTTS_DESCRIPCION AS PRODUC_DESCRIPCION,
ENC.SYSTTS_CODIGO_K AS PROPRE_CODIGO_K,
ENC.LIQCES_FECHA AS FACDOC_FECHA,
'CARGO' AS TPO_VTA,
DET.LIQCESD_CANTIDAD AS PIEZAS,
0.0 AS COSTO,
0.0 AS VENTA
FROM
LIQ_CARGOESPENC ENC LEFT JOIN LIQ_CARGOESPDET DET ON
ENC.SYSUDN_CODIGO_K = DET.SYSUDN_CODIGO_K
AND ENC.SYSTRA_CODIGO_K = DET.SYSTRA_CODIGO_K
AND ENC.LIQCES_SERIE_K = DET.LIQCES_SERIE_K
AND ENC.LIQCES_FOLIO_K = DET.LIQCES_FOLIO_K
LEFT JOIN SYS_TRANSACTIPO TRA ON
TRA.SYSTRA_CODIGO_K = ENC.SYSTRA_CODIGO_K
AND TRA.SYSTTP_CODIGO_K = ENC.SYSTTP_CODIGO_K
LEFT JOIN SYS_TRANSACSUBTIPO TPO ON
TPO.SYSTRA_CODIGO_K = ENC.SYSTRA_CODIGO_K
AND TPO.SYSTRA_CODIGO_K = TRA.SYSTRA_CODIGO_K
AND TPO.SYSTTP_CODIGO_K = TRA.SYSTTP_CODIGO_K
AND TPO.SYSTTS_CODIGO_K = ENC.SYSTTS_CODIGO_K
AND TPO.SYSTTP_CODIGO_K = ENC.SYSTTP_CODIGO_K
WHERE ENC.SYSUDN_CODIGO_K IN ('UDN_01','UDN_02','UDN_03','UDN_04','UDN_05','UDN_06')
AND ENC.LIQCES_FECHA BETWEEN @FECHA_INI AND @FECHA_FIN
AND DET.PRODUC_CODIGO_K BETWEEN '00' AND 'zz'
AND ENC.S_MAQEDO <> 20
GROUP  BY
ENC.SYSUDN_CODIGO_K,
ENC.LIQUID_REFERENCIA,
DET.PRODUC_CODIGO_K,
TPO.SYSTTS_DESCRIPCION,
ENC.SYSTTS_CODIGO_K,
ENC.LIQCES_FECHA,
DET.LIQCESD_CANTIDAD
),
TMP_LIQUID AS(
SELECT
SYSUDN_CODIGO_K,
LIQUID_REFERENCIA,
SUM (CASE WHEN VENTA > 0 THEN VENTA ELSE 0 END) AS LIQUIDADO
FROM
TMP_VENTAS1
GROUP BY
SYSUDN_CODIGO_K,
LIQUID_REFERENCIA
),
TMP_LIQCAR AS (
SELECT
TMP_LIQUID.SYSUDN_CODIGO_K,
TMP_LIQUID.LIQUID_REFERENCIA,
(LIQUIDADO -  SUM(EFE.LIQCEF_VALOR)) AS TOTAL_VENTA
FROM
LIQ_CARGOEFE EFE LEFT JOIN TMP_LIQUID ON
EFE.LIQUID_REFERENCIA = TMP_LIQUID.LIQUID_REFERENCIA
WHERE
TMP_LIQUID.LIQUID_REFERENCIA IS NOT NULL
AND EFE.SYSUDN_CODIGO_K IN ('UDN_01','UDN_02','UDN_03','UDN_04','UDN_05','UDN_06')
AND EFE.LIQCEF_FECHA BETWEEN @FECHA_INI AND @FECHA_FIN
GROUP BY
TMP_LIQUID.SYSUDN_CODIGO_K,
TMP_LIQUID.LIQUID_REFERENCIA,
LIQUIDADO
),
TMP_LIQUIDADO AS (
SELECT
TMP_LIQUID.SYSUDN_CODIGO_K,
TMP_LIQUID.LIQUID_REFERENCIA,
TMP_LIQUID.LIQUIDADO,
CASE WHEN TMP_LIQCAR.TOTAL_VENTA IS NOT NULL THEN TMP_LIQCAR.TOTAL_VENTA ELSE TMP_LIQUID.LIQUIDADO END AS TOTAL_VENTA
FROM
TMP_LIQUID
LEFT JOIN TMP_LIQCAR ON
TMP_LIQUID.SYSUDN_CODIGO_K = TMP_LIQCAR.SYSUDN_CODIGO_K
AND TMP_LIQUID.LIQUID_REFERENCIA = TMP_LIQCAR.LIQUID_REFERENCIA
GROUP BY
TMP_LIQUID.SYSUDN_CODIGO_K,
TMP_LIQUID.LIQUID_REFERENCIA,
TMP_LIQUID.LIQUIDADO,
TMP_LIQCAR.SYSUDN_CODIGO_K,
TMP_LIQCAR.LIQUID_REFERENCIA,
TMP_LIQCAR.TOTAL_VENTA
),
PREVIO AS (
SELECT
T.SYSUDN_CODIGO_K, T.LIQUID_REFERENCIA, T.CTECLI_CODIGO_K,
L.CFGEPL_CODIGO_K, E.CFGEPL_NOMBRE, L.CFGECO_CODIGO_K, O.CFGECO_DESCRIPCION,
L.LIQUID_AYUDANTE1, L.LIQUID_AYUDANTE2,
L.LIQUID_FECHAENT, L.VTARUT_CODIGO_K, R.VTARUT_DESCRIPCION, T.PRODUC_CODIGO_K, T.PRODUC_DESCRIPCION,
T.PROPRE_CODIGO_K, T.FACDOC_FECHA, T.TPO_VTA,
SUM(T.PIEZAS) AS PIEZAS,
T.COSTO AS COSTO,
SUM (T.VENTA) AS IMPORTE,
Q.TOTAL_VENTA AS VENTA
FROM
TMP_VENTAS1 T
INNER JOIN LIQ_LIQUIDACION L ON
T.LIQUID_REFERENCIA = L.LIQUID_REFERENCIA
LEFT OUTER JOIN CFG_EMPLEADO E ON
L.CFGEPL_CODIGO_K = E.CFGEPL_CODIGO_K
LEFT OUTER JOIN CFG_ECONOMICO O ON
L.CFGECO_CODIGO_K = O.CFGECO_CODIGO_K
LEFT OUTER JOIN VTA_RUTA R ON
L.VTARUT_CODIGO_K = R.VTARUT_CODIGO_K
LEFT OUTER JOIN TMP_LIQUIDADO Q ON
L.LIQUID_REFERENCIA = Q.LIQUID_REFERENCIA
WHERE
T.PRODUC_CODIGO_K IS NOT NULL
AND T.PRODUC_DESCRIPCION IS NOT NULL
AND T.CTECLI_CODIGO_K NOT IN ( 'TIPO_CONTADO' )
AND L.VTARUT_CODIGO_K BETWEEN '00' AND 'zz'
GROUP BY
T.SYSUDN_CODIGO_K, T.LIQUID_REFERENCIA, T.CTECLI_CODIGO_K,
L.CFGEPL_CODIGO_K, E.CFGEPL_NOMBRE, L.CFGECO_CODIGO_K, O.CFGECO_DESCRIPCION,
L.LIQUID_AYUDANTE1, L.LIQUID_AYUDANTE2,
L.LIQUID_FECHAENT, L.VTARUT_CODIGO_K, R.VTARUT_DESCRIPCION, T.PRODUC_CODIGO_K, T.PRODUC_DESCRIPCION,
T.PROPRE_CODIGO_K, T.FACDOC_FECHA, T.TPO_VTA, Q.TOTAL_VENTA, T.COSTO, T.VENTA
),
TMP_ULTIMO AS (
SELECT
SYSUDN_CODIGO_K,
LIQUID_REFERENCIA,
CTECLI_CODIGO_K,
CFGEPL_CODIGO_K,
CFGEPL_NOMBRE,
CFGECO_CODIGO_K,
CFGECO_DESCRIPCION,
LIQUID_AYUDANTE1,
LIQUID_AYUDANTE2,
LIQUID_FECHAENT,
VTARUT_CODIGO_K,
VTARUT_DESCRIPCION,
PRODUC_CODIGO_K,
PRODUC_DESCRIPCION,
PROPRE_CODIGO_K,
FACDOC_FECHA,
TPO_VTA,
PIEZAS,
COSTO,
IMPORTE,
CASE
WHEN IMPORTE > 0  THEN
SUM(IMPORTE)
ELSE
0
END LIQUIDACION,
VENTA
FROM PREVIO
GROUP BY
SYSUDN_CODIGO_K,
LIQUID_REFERENCIA,
CTECLI_CODIGO_K,
CFGEPL_CODIGO_K,
CFGEPL_NOMBRE,
CFGECO_CODIGO_K,
CFGECO_DESCRIPCION,
LIQUID_AYUDANTE1,
LIQUID_AYUDANTE2,
LIQUID_FECHAENT,
VTARUT_CODIGO_K,
VTARUT_DESCRIPCION,
PRODUC_CODIGO_K,
PRODUC_DESCRIPCION,
PROPRE_CODIGO_K,
FACDOC_FECHA,
TPO_VTA,
PIEZAS,
COSTO,
IMPORTE,
VENTA
)
SELECT
SYSUDN_CODIGO_K,
LIQUID_REFERENCIA,
CTECLI_CODIGO_K,
CFGEPL_CODIGO_K,
CFGEPL_NOMBRE,
CFGECO_CODIGO_K,
CFGECO_DESCRIPCION,
LIQUID_AYUDANTE1,
LIQUID_AYUDANTE2,
LIQUID_FECHAENT,
VTARUT_CODIGO_K,
VTARUT_DESCRIPCION,
PRODUC_CODIGO_K,
PRODUC_DESCRIPCION,
PROPRE_CODIGO_K,
FACDOC_FECHA,
TPO_VTA,
SUM (PIEZAS) AS PIEZAS ,
COSTO,
SUM (IMPORTE) AS IMPORTE,
SUM ( LIQUIDACION) AS LIQUIDACION,
VENTA
FROM TMP_ULTIMO
GROUP BY
SYSUDN_CODIGO_K,
LIQUID_REFERENCIA,
CTECLI_CODIGO_K,
CFGEPL_CODIGO_K,
CFGEPL_NOMBRE,
CFGECO_CODIGO_K,
CFGECO_DESCRIPCION,
LIQUID_AYUDANTE1,
LIQUID_AYUDANTE2,
LIQUID_FECHAENT,
VTARUT_CODIGO_K,
VTARUT_DESCRIPCION,
PRODUC_CODIGO_K,
PRODUC_DESCRIPCION,
PROPRE_CODIGO_K,
FACDOC_FECHA,
TPO_VTA,
COSTO,
VENTA
ORDER BY
VTARUT_CODIGO_K,
SYSUDN_CODIGO_K,
LIQUID_REFERENCIA,
CTECLI_CODIGO_K,
CFGEPL_CODIGO_K,
CFGEPL_NOMBRE,
CFGECO_CODIGO_K,
CFGECO_DESCRIPCION,
LIQUID_AYUDANTE1,
LIQUID_AYUDANTE2,
LIQUID_FECHAENT,
VTARUT_DESCRIPCION,
PRODUC_CODIGO_K,
PRODUC_DESCRIPCION,
PROPRE_CODIGO_K,
FACDOC_FECHA,
TPO_VTA,
COSTO,
VENTA
SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
END TRY
BEGIN CATCH
SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
END CATCH;
